### ISSUE TITLE
python2.7 about to be deprecated

### ISSUE THREAD

**Issue by jeetee** [musescore/tx2s3#15]
Travis utters a warning about python 2.7 being outdated:

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7

Updating python means moving to 3.x, so that could be a bit more convoluted

**Comment by anatoly-os** [comment]
Should be fixed in https://github.com/musescore/tx2s3/commit/dc2862085199d169ddafdcf48eb1b32b8f02f13b
